name = "glelm"
version = "0.1.0"

description = "Elm parser written in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "bilus", repo = "glelm" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
nibble = ">= 1.1.3 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
glance = ">= 2.0.0 and < 3.0.0"
glance_printer = ">= 2.0.0 and < 3.0.0"
gap = ">= 1.1.3 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
